// ─────────────────────────────────────────
//  Saptasur Backdrop — Config & Types
//  Edit CONFIG below to update the show
// ─────────────────────────────────────────

export class Singer {
  name:  string
  image: string  // Cloudinary URL or /public path

  constructor(name: string, image: string) {
    this.name  = name
    this.image = image
  }
}

export interface SongEntry {
  song:         string   // Song title shown on screen
  singer:       Singer   // Singer object — name + image come from here
  lataOriginal: string   // Original song name by Lata Ji
  film:         string   // Film or album name
  year:         string   // Year of original recording
  story?:        string
}

export interface BackdropConfig {
  durationHours: number
  logos: {
    school: string       // left of timer
    ngo1:   string       // right of timer
    ngo2:   string       // right of timer
  }
  songs: SongEntry[]
}

// ─── Singers ──────────────────────────────────────────────────────────────────
// Add a new Singer here once, then reuse across as many songs as needed.

const SINGERS = {
  nishad: new Singer(
    "Nishad Deshmukh",
    "https://res.cloudinary.com/dzxvxhf1s/image/upload/v1773660770/Saptsur/WhatsApp_Image_2026-03-16_at_4.28.31_PM_ivwfno.jpg",
  ),
  meera: new Singer(
    "Meera Kulkarni",
    "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&q=80",
  ),
  rohan: new Singer(
    "Rohan Joshi",
    "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80",
  ),
   dummy: new Singer(
    "Dummy",
    "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80",
  ),
  // Add more singers here...
}

// ─── Config ───────────────────────────────────────────────────────────────────

const CONFIG: BackdropConfig = {
  durationHours: 3,

  logos: {
    school: "/assets/ssv-logo.jpeg",
    ngo1:   "/assets/Adhar_ashram_logo-1.webp",
    ngo2:   "/assets/I_Prog_LOGO.jpeg",
  },

  songs: [
    // ── Session 1 ──────────────────────────
    {
      song:         "Shubhankaroti Mhana",
      singer:       SINGERS.dummy,
      lataOriginal: "Shubhankaroti Mhana",
      film:         "Devotional — Marathi",
      year:         "—",
      story:        "A traditional Marathi evening prayer, this shloka was among the devotional verses Lata Mangeshkar recorded early in her career as a tribute to her Maharashtrian roots.",
    },
    {
      song:         "Tuz Magto Mi Aata",
      singer:       SINGERS.dummy,
      lataOriginal: "Tuz Magto Mi Aata",
      film:         "Devotional — Marathi",
      year:         "—",
      story:        "A heartfelt Marathi devotional, this prayer of supplication is one of the beloved bhakti compositions Lata recorded with characteristic simplicity and deep feeling.",
    },
    {
      song:         "Shri Ram",
      singer:       SINGERS.dummy,
      lataOriginal: "Shri Ram Chandra Kripalu",
      film:         "Devotional",
      year:         "—",
      story:        "Lata Mangeshkar held Ram bhajans especially dear — she recorded this devotional with a purity of voice that she herself said came only when she felt genuine reverence.",
    },
    {
      song:         "Gagan Sadan",
      singer:       SINGERS.dummy,
      lataOriginal: "Gagan Sadan Tejomaya",
      film:         "Umbartha",
      year:         "1981",
      story:        "Composed by Hridaynath Mangeshkar for the Marathi film Umbartha, this luminous prayer is widely considered one of Lata's finest Marathi recordings, earning devoted fans decades after its release.",
    },
    {
      song:         "Vithai Kitai",
      singer:       SINGERS.dummy,
      lataOriginal: "Vithai Kitai Ughad Dwar",
      film:         "Devotional — Marathi",
      year:         "—",
      story:        "A Marathi abhang addressed to Vitthal of Pandharpur, Lata sang such Varkari compositions with a folk simplicity that made them accessible to millions of devotees.",
    },
    {
      song:         "Lek Ladki",
      singer:       SINGERS.dummy,
      lataOriginal: "Lek Ladki Ya Gharat",
      film:         "Marathi — Folk",
      year:         "—",
      story:        "A beloved Marathi folk song celebrating the birth of a daughter, Lata's rendition brought warmth and tenderness to a tradition that had long been sung at family celebrations.",
    },
    {
      song:         "Sunya Sunya Maifilit",
      singer:       SINGERS.dummy,
      lataOriginal: "Sunya Sunya Maifilit Majhya",
      film:         "Umbartha",
      year:         "1981",
      story:        "From the landmark Marathi film Umbartha, this melancholic gem composed by Hridaynath Mangeshkar showcases Lata at her most restrained and emotionally devastating best.",
    },
    {
      song:         "Ya Chimnyano Parat Fira",
      singer:       SINGERS.dummy,
      lataOriginal: "Ya Chimnyano Parat Fira",
      film:         "Marathi — Folk",
      year:         "—",
      story:        "One of Lata's iconic Marathi nature songs, its gentle melody about the return of sparrows became a staple of Marathi music programmes across Maharashtra.",
    },
    {
      song:         "Runuzunu / Payoji Maine",
      singer:       SINGERS.dummy,
      lataOriginal: "Payoji Maine Ram Ratan Dhan Payo",
      film:         "Devotional — Meerabai",
      year:         "—",
      story:        "Lata considered Meerabai's bhajans among the most spiritually demanding music she ever recorded, requiring the singer to surrender completely to the emotion of divine longing.",
    },
    {
      song:         "Prema Kay Deu Tula",
      singer:       SINGERS.dummy,
      lataOriginal: "Prema Kay Deu Tula",
      film:         "Marathi",
      year:         "—",
      story:        "A tender Marathi love song, this composition captures the devotional quality Lata brought even to romantic material — a hallmark of her unique approach to melody.",
    },
    {
      song:         "Mi Katyatun Chalun Thakle",
      singer:       SINGERS.dummy,
      lataOriginal: "Mi Katyatun Chalun Thakle",
      film:         "Marathi",
      year:         "—",
      story:        "This introspective Marathi song about a weary journey resonated deeply with audiences, and Lata's nuanced interpretation drew out its underlying emotion with quiet power.",
    },
    {
      song:         "Malyachya Malyamandi",
      singer:       SINGERS.dummy,
      lataOriginal: "Malyachya Malyamandi",
      film:         "Marathi — Folk",
      year:         "—",
      story:        "A traditional Marathi folk melody set in a flower garden, Lata's fresh and unhurried rendition made it a perennial favourite at cultural programmes across Maharashtra.",
    },
    {
      song:         "Sandhikali Ya Asha",
      singer:       SINGERS.dummy,
      lataOriginal: "Sandhikali Ya",
      film:         "Marathi",
      year:         "—",
      story:        "A lyrical Marathi evening song, its gentle imagery of dusk and hope reflects the poetic sensibility that made Lata's Marathi recordings so beloved among discerning listeners.",
    },
    {
      song:         "Maje Rani Maje Moga",
      singer:       SINGERS.dummy,
      lataOriginal: "Maje Rani Maje Moga",
      film:         "Marathi",
      year:         "—",
      story:        "This playful Marathi song carries the warmth of affectionate address; Lata's ability to move between reverence and lightness within a single style made such songs feel genuinely alive.",
    },
    {
      song:         "Airanichya Deva",
      singer:       SINGERS.dummy,
      lataOriginal: "Airanichya Deva Tula",
      film:         "Devotional — Marathi",
      year:         "—",
      story:        "A celebrated Marathi devotional addressed to a folk deity, this song holds a special place in Maharashtra's musical tradition and was brought to wider prominence through Lata's recording.",
    },
    {
      song:         "Daul Morachya",
      singer:       SINGERS.dummy,
      lataOriginal: "Daul Morachya",
      film:         "Marathi — Folk",
      year:         "—",
      story:        "A lively Marathi folk song evoking the drumbeat and dance of the peacock, Lata brought controlled exuberance to this composition that made it a favourite at festive gatherings.",
    },
    {
      song:         "Shodhu Mi",
      singer:       SINGERS.dummy,
      lataOriginal: "Shodhu Mi Kasa Tula",
      film:         "Marathi",
      year:         "—",
      story:        "A contemplative Marathi song of searching and longing, Lata's transparent vocal quality made the inner turmoil of the lyrics feel effortlessly expressed.",
    },
    {
      song:         "Latpat",
      singer:       SINGERS.dummy,
      lataOriginal: "Kanti Nav Navti",
      film:         "Marathi — Folk",
      year:         "—",
      story:        "A spirited Marathi folk song celebrating newlywed joy, the energy and playfulness Lata brought to such festive material showed the remarkable range she maintained throughout her career.",
    },
    {
      song:         "Asa Nesun Shalu",
      singer:       SINGERS.dummy,
      lataOriginal: "Asa Nesun Shalu",
      film:         "Marathi — Folk",
      year:         "—",
      story:        "This graceful Marathi song describing a woman draping her saree is widely loved for both its melody and its tender cultural imagery, popularised through Lata's definitive recording.",
    },
    {
      song:         "Reshamachya Reghani",
      singer:       SINGERS.dummy,
      lataOriginal: "Reshamachya Reghani",
      film:         "Marathi — Folk",
      year:         "—",
      story:        "Evoking the shimmer of silk threads, this Marathi folk melody is one of Lata's most visually evocative recordings — her voice painting textures as much as notes.",
    },
    {
      song:         "Mi Dolkar",
      singer:       SINGERS.dummy,
      lataOriginal: "Mi Dolkar",
      film:         "Marathi",
      year:         "—",
      story:        "A buoyant Marathi song full of movement and rhythm, Lata's rendering of this composition captures the carefree spirit of traditional Maharashtrian folk celebration.",
    },
 
    // ── Session 2 ──────────────────────────
    {
      song:         "Shiv Kalyan Raja",
      singer:       SINGERS.dummy,
      lataOriginal: "Shiv Kalyan Raja",
      film:         "Devotional — Marathi",
      year:         "—",
      story:        "A rousing Marathi ode to Chhatrapati Shivaji, this patriotic devotional is frequently sung at cultural programmes and carries the pride of Maharashtra's historical legacy.",
    },
    {
      song:         "Akheracha Ha Tula",
      singer:       SINGERS.dummy,
      lataOriginal: "Akheracha Ha Tula Namaskar Maaza",
      film:         "Marathi",
      year:         "—",
      story:        "An emotive farewell song in Marathi, its poignant lyrics of final salutation were given full weight by Lata's capacity to convey deep feeling without melodramatic excess.",
    },
    {
      song:         "Ne Majsi Ne",
      singer:       SINGERS.dummy,
      lataOriginal: "Ne Majsi Ne Parat Matrubhumila",
      film:         "Devotional — Patriotic",
      year:         "—",
      story:        "Written by Bal Gangadhar Tilak, this Marathi poem of longing for the motherland was set to music and recorded by Lata as an act of deep patriotic reverence.",
    },
    {
      song:         "Jai Dev Jai Dev",
      singer:       SINGERS.dummy,
      lataOriginal: "Jai Dev Jai Dev Jai Mangalmoorti",
      film:         "Devotional — Marathi",
      year:         "—",
      story:        "A beloved Marathi aarti to Lord Ganesha, Lata recorded this auspicious prayer with the disciplined devotion she always brought to religious compositions.",
    },
    {
      song:         "Marathi Paul Padte",
      singer:       SINGERS.dummy,
      lataOriginal: "Marathi Paul Padte Pudhe",
      film:         "Patriotic — Marathi",
      year:         "—",
      story:        "A stirring march celebrating the Marathi spirit of progress, this song's infectious momentum reflects the collective pride Lata helped crystallise through her patriotic recordings.",
    },
    {
      song:         "He Hindu Narsimha",
      singer:       SINGERS.dummy,
      lataOriginal: "He Hindu Narsimha",
      film:         "Devotional",
      year:         "—",
      story:        "A powerful invocation of Lord Narasimha, this devotional composition required the kind of fearless vocal projection that Lata consistently delivered in her bhakti recordings.",
    },
    {
      song:         "Shur Amhi Sardar",
      singer:       SINGERS.dummy,
      lataOriginal: "Shur Amhi Sardar",
      film:         "Patriotic — Marathi",
      year:         "—",
      story:        "An anthem of Marathi warrior pride, this bold composition became a standard of cultural programmes and has been passed down through generations of Maharashtra's musical tradition.",
    },
    {
      song:         "Jayostute",
      singer:       SINGERS.dummy,
      lataOriginal: "Jayostute Shri Mahannaryae",
      film:         "Patriotic — Marathi",
      year:         "—",
      story:        "Written by Vinayak Damodar Savarkar as a salutation to the motherland, Lata's recording of this iconic Marathi patriotic poem gave it renewed life for millions of listeners.",
    },
    {
      song:         "Vedat Marathe Veer",
      singer:       SINGERS.dummy,
      lataOriginal: "Vedat Marathe Veer Daudat Aale",
      film:         "Patriotic — Marathi",
      year:         "—",
      story:        "A rousing Marathi ballad celebrating the valour of Maratha warriors, this song has been a staple of Maharashtra Day celebrations and is held close to the Marathi cultural identity.",
    },
 
    // ── Session 3 ──────────────────────────
    {
      song:         "Tere Sur Aur Mere Geet",
      singer:       SINGERS.dummy,
      lataOriginal: "Tere Sur Aur Mere Geet",
      film:         "Goonj Uthi Shehnai",
      year:         "1959",
      story:        "Composed by Vasant Desai for this musical drama, this song about the union of voice and instrument reflects the collaborative spirit that defined Lata's most celebrated recordings.",
    },
    {
      song:         "Aaja Re Pardesi",
      singer:       SINGERS.dummy,
      lataOriginal: "Aaja Re Pardesi",
      film:         "Madhumati",
      year:         "1958",
      story:        "Lata won her first Filmfare Award for this Salil Chowdhury composition — the song was initially rejected by director Bimal Roy, but Lata threatened to stop singing for him, and it stayed in the film.",
    },
    {
      song:         "Phool Tumhein Bheja Hai",
      singer:       SINGERS.dummy,
      lataOriginal: "Phool Tumhein Bheja Hai Khat Mein",
      film:         "Saraswatichandra",
      year:         "1968",
      story:        "Composed by Kalyanji-Anandji, this delicate song of longing became one of the most requested compositions from Lata's vast catalogue, its simplicity disguising deep emotional precision.",
    },
    {
      song:         "Yara Sili Sili",
      singer:       SINGERS.dummy,
      lataOriginal: "Yara Sili Sili Birha Ki Raat",
      film:         "Lekin",
      year:         "1991",
      story:        "Composed by Hridaynath Mangeshkar and penned by Gulzar, this haunting song from Lekin earned Lata a National Film Award — her brother's music drawing out one of her most ethereal performances.",
    },
    {
      song:         "Teri Ankhon Ke Siwa",
      singer:       SINGERS.dummy,
      lataOriginal: "Teri Ankhon Ke Siwa Duniya Mein",
      film:         "Chirag",
      year:         "1969",
      story:        "Madan Mohan's spare and aching melody gave Lata room to convey absolute devotion; the song has been described as one of the purest expressions of the singer-composer partnership.",
    },
    {
      song:         "Naam Gum Jayega",
      singer:       SINGERS.dummy,
      lataOriginal: "Naam Gum Jayega",
      film:         "Kinara",
      year:         "1977",
      story:        "A duet with Bhupinder Singh composed by R.D. Burman to Gulzar's lyrics, this philosophical meditation on art outlasting its creator is considered one of Hindi cinema's most moving songs.",
    },
    {
      song:         "Aayega Aayega",
      singer:       SINGERS.dummy,
      lataOriginal: "Aayega Aayega Aane Wala",
      film:         "Mahal",
      year:         "1949",
      story:        "One of Lata's earliest defining recordings, this eerie and beautiful song from Mahal established her as a singular voice — Khemchand Prakash's composition made her a household name overnight.",
    },
    {
      song:         "Ye Jivan Hai",
      singer:       SINGERS.dummy,
      lataOriginal: "Ye Jivan Hai Is Jivan Ka",
      film:         "Piya Ka Ghar",
      year:         "1972",
      story:        "Laxmikant-Pyarelal's warm and affirmative composition gave Lata a melody that celebrated life's simple joys; its straightforward optimism made it a favourite across generations.",
    },
    {
      song:         "Do Pal Ruka",
      singer:       SINGERS.dummy,
      lataOriginal: "Do Pal Ruka Khwabon Ka Karvan",
      film:         "Veer-Zaara",
      year:         "2004",
      story:        "One of Lata's final celebrated recordings, this Madan Mohan composition — orchestrated by his son Sanjeev Kohli — showed that her capacity for aching longing remained undiminished in her seventies.",
    },
    {
      song:         "Mere Naina",
      singer:       SINGERS.dummy,
      lataOriginal: "Mere Naina Sawan Bhadon",
      film:         "Mehbooba",
      year:         "1976",
      story:        "R.D. Burman set this monsoon song of tearful longing to an irresistible melody; Lata's effortlessly evocative rendering made it one of the most enduring songs of the 1970s.",
    },
    {
      song:         "Kahi Deep Jale Kahi Dil",
      singer:       SINGERS.dummy,
      lataOriginal: "Kahi Deep Jale Kahi Dil",
      film:         "Bees Saal Baad",
      year:         "1962",
      story:        "Hemant Kumar composed this atmospheric nocturne for the thriller Bees Saal Baad; Lata's performance, suffused with mystery and yearning, has made it an all-time classic of Hindi film music.",
    },
    {
      song:         "Rasm-e-Ulfat",
      singer:       SINGERS.dummy,
      lataOriginal: "Rasm-e-Ulfat Ko Nibhate",
      film:         "Dil Hi To Hai",
      year:         "1963",
      story:        "Roshan's melodic architecture and Lata's command of Urdu diction combined to make this ghazal-tinged song one of the most refined recordings of her early 1960s peak.",
    },
    {
      song:         "Aake Teri Bahon Mein",
      singer:       SINGERS.dummy,
      lataOriginal: "Aake Teri Bahon Mein",
      film:         "Aap Ki Kasam",
      year:         "1974",
      story:        "R.D. Burman's lilting melody and Anand Bakshi's simple, warm lyrics gave Lata a love song of uncomplicated joy — a quality she rendered with an ease that took years of craft to perfect.",
    },
    {
      song:         "Patzad Saawan",
      singer:       SINGERS.dummy,
      lataOriginal: "Patzad Saawan Basant Bahar",
      film:         "Sargam",
      year:         "1950",
      story:        "An early gem showcasing Lata's command of classical-influenced melody, this song about the changing seasons was one of the recordings that first drew serious musicians' attention to her talent.",
    },
    {
      song:         "Sun Beliya",
      singer:       SINGERS.dummy,
      lataOriginal: "Sun Beliya",
      film:         "Marathi",
      year:         "—",
      story:        "A gentle Marathi melody addressed to the beloved, the intimacy and warmth Lata brought to such small-scale romantic songs made them feel like private conversations rendered in music.",
    },
    {
      song:         "Pyar Hua Ikrar Hua",
      singer:       SINGERS.dummy,
      lataOriginal: "Pyar Hua Ikrar Hua Hai",
      film:         "Shree 420",
      year:         "1955",
      story:        "Sung with Manna Dey under Shankar-Jaikishan's direction, this rain-soaked duet from Raj Kapoor's Shree 420 became one of Hindi cinema's most iconic romantic images.",
    },
 
    // ── Session 4 ──────────────────────────
    {
      song:         "Jau Tore Charan",
      singer:       SINGERS.dummy,
      lataOriginal: "Jau Tore Charan Kahan",
      film:         "Devotional",
      year:         "—",
      story:        "A devotional in the dhrupad tradition, this composition of total surrender at the divine feet was one of the kinds of bhakti music Lata approached with the most personal reverence.",
    },
    {
      song:         "Ajeeb Dastan Hai Yeh",
      singer:       SINGERS.dummy,
      lataOriginal: "Ajeeb Dastan Hai Yeh",
      film:         "Dil Apna Aur Preet Parayi",
      year:         "1960",
      story:        "Shankar-Jaikishan's Hawaiian-tinged composition gave Lata a song of wistful resignation that Meena Kumari lip-synced on screen; its deceptive simplicity conceals extraordinary emotional depth.",
    },
    {
      song:         "Bekhudi Mein Sanam",
      singer:       SINGERS.dummy,
      lataOriginal: "Bekhudi Mein Sanam",
      film:         "Aap Ki Parchhaiyan",
      year:         "1964",
      story:        "A song of helpless, ecstatic love composed by Ravi, Lata's rendering captures the dizzying sensation of complete emotional surrender that the lyrics describe so precisely.",
    },
    {
      song:         "Mere Pyar Ki",
      singer:       SINGERS.dummy,
      lataOriginal: "Mere Pyar Ki Umar Ho Itni Sanam",
      film:         "Sachai",
      year:         "1969",
      story:        "A prayer for love to last a lifetime, this Laxmikant-Pyarelal composition gave Lata a melody of aching sincerity that audiences embraced as their own private longing.",
    },
    {
      song:         "Yuhin Tum Mujhse Baat Karti Ho",
      singer:       SINGERS.dummy,
      lataOriginal: "Yuhin Tum Mujhse Baat Karti Ho",
      film:         "Ek Baar Muskura Do",
      year:         "1972",
      story:        "A playful love duet originally sung with Kishore Kumar, this Laxmikant-Pyarelal composition sparkles with lighthearted affection that Lata rendered with characteristic precision.",
    },
    {
      song:         "Kabhi Tu Chhaliya",
      singer:       SINGERS.dummy,
      lataOriginal: "Badal Yun Garajta Hai",
      film:         "Ek Duje Ke Liye",
      year:         "1981",
      story:        "Laxmikant-Pyarelal's monsoon melody from the blockbuster Ek Duje Ke Liye gave Lata a song of passionate, stormy longing that became inseparable from the film's tragic love story.",
    },
    {
      song:         "Dil To Pagal Hai",
      singer:       SINGERS.dummy,
      lataOriginal: "Dil To Pagal Hai",
      film:         "Dil To Pagal Hai",
      year:         "1997",
      story:        "One of Lata's later defining recordings, Uttam Singh's composition for this Yash Chopra film captured a timeless romantic restlessness in a voice that had lost none of its expressive power.",
    },
    {
      song:         "Yeh Raat Bhigi Bhigi",
      singer:       SINGERS.dummy,
      lataOriginal: "Yeh Raat Bhigi Bhigi",
      film:         "Chori Chori",
      year:         "1956",
      story:        "Shankar-Jaikishan's nocturnal duet with Manna Dey from Chori Chori is among Lata's most beloved recordings — its romantic mood perfectly matched the dreamy, moon-drenched scene it accompanied.",
    },
    {
      song:         "Gore Gore",
      singer:       SINGERS.dummy,
      lataOriginal: "Gore Gore O Banke Chhore",
      film:         "Samadhi",
      year:         "1950",
      story:        "One of Lata's early playful numbers, this C. Ramchandra composition showed her natural ease with folk-influenced melody — a lightness that would come to define some of her most loved songs.",
    },
    {
      song:         "Ungli Mein Angoothi",
      singer:       SINGERS.dummy,
      lataOriginal: "Ungli Mein Angoothi Angoothi Mein Nag",
      film:         "Mughal-E-Azam",
      year:         "1960",
      story:        "A spirited, semi-classical piece from the epic Mughal-E-Azam, Naushad's composition gave Lata an opportunity to display the classical rigour that underpinned her apparently effortless style.",
    },
    {
      song:         "Chup Gaye Sare Nazare",
      singer:       SINGERS.dummy,
      lataOriginal: "Chup Gaye Sare Nazare",
      film:         "Dost",
      year:         "1974",
      story:        "Laxmikant-Pyarelal composed this dreamy nocturne for Dost; Lata's hushed, contemplative rendition of the song's evening imagery became one of the decade's most atmospheric recordings.",
    },
    {
      song:         "Aja Sanam",
      singer:       SINGERS.dummy,
      lataOriginal: "Aja Sanam Madhur Chandni Mein Hum",
      film:         "Chori Chori",
      year:         "1956",
      story:        "Another jewel from Chori Chori, this Shankar-Jaikishan duet with Manna Dey invited listeners into a world of silver moonlight and uncomplicated romantic joy.",
    },
    {
      song:         "Luka Chhupi",
      singer:       SINGERS.dummy,
      lataOriginal: "Luka Chhupi Bahut Hui",
      film:         "Rang De Basanti",
      year:         "2006",
      story:        "A.R. Rahman composed this tender lullaby for Rang De Basanti, and Lata's frail, luminous voice transformed it into something both intimate and achingly final — one of her last great recordings.",
    },
    {
      song:         "Bol Gori Bol Tera Kaun Piya",
      singer:       SINGERS.dummy,
      lataOriginal: "Bol Gori Bol Tera Kaun Piya",
      film:         "Albela",
      year:         "1951",
      story:        "C. Ramchandra's irresistible composition from Albela gave Lata a number full of folk charm and street-corner vitality — a side of her artistry that delighted fans alongside her classical recordings.",
    },
    {
      song:         "Upar Khuda",
      singer:       SINGERS.dummy,
      lataOriginal: "Upar Khuda Aasman Neeche",
      film:         "Kala Bazar",
      year:         "1960",
      story:        "S.D. Burman's playful composition from Kala Bazar captured Lata at her most carefree; the song's gentle teasing tone showed the full range of registers she could inhabit with equal ease.",
    },
 
    // ── Session 5 ──────────────────────────
    {
      song:         "Rahe Na Rahe Hum",
      singer:       SINGERS.dummy,
      lataOriginal: "Rahe Na Rahe Hum Mehka Karenge",
      film:         "Mamta",
      year:         "1966",
      story:        "Roshan's haunting melody and Majrooh Sultanpuri's poetic lyrics gave Lata a song about the immortality of love — she poured into it a depth of feeling that has moved listeners for six decades.",
    },
    {
      song:         "Gum Hain Kisiki",
      singer:       SINGERS.dummy,
      lataOriginal: "Gum Hain Kisiki Pyar Mein",
      film:         "Seeta Aur Geeta",
      year:         "1972",
      story:        "R.D. Burman's infectious melody and Lata's sparkling delivery made this song from Seeta Aur Geeta an instant hit — its playful energy a perfect match for the film's double-role premise.",
    },
    {
      song:         "Mehboob Mere",
      singer:       SINGERS.dummy,
      lataOriginal: "Mehboob Mere Mehboob Mere",
      film:         "Heera Panna",
      year:         "1973",
      story:        "R.D. Burman's melody for this declaration of love has an intoxicating warmth; Lata's rendering lingers in the memory long after the film itself has faded from public consciousness.",
    },
    {
      song:         "Kitna Pyara Wada",
      singer:       SINGERS.dummy,
      lataOriginal: "Kitna Pyara Wada Hai In Meethi",
      film:         "Caravan",
      year:         "1971",
      story:        "Sonik-Omi's composition for Caravan became one of Lata's most warmly received songs of the period — its promise of love as simple and dependable as sweetness itself.",
    },
    {
      song:         "Patta Patta Buta Buta",
      singer:       SINGERS.dummy,
      lataOriginal: "Patta Patta Buta Buta",
      film:         "Ek Nazar",
      year:         "1972",
      story:        "A Madan Mohan ghazal of extraordinary refinement, this recording from Ek Nazar is considered among the finest examples of Lata's mastery of Urdu diction and restrained emotional expression.",
    },
    {
      song:         "Bhigi Bhigi Raaton Mein",
      singer:       SINGERS.dummy,
      lataOriginal: "Bhigi Bhigi Raaton Mein",
      film:         "Ajnabee",
      year:         "1974",
      story:        "R.D. Burman's atmospheric rain song from Ajnabee, with its hypnotic rhythm, gave Lata a backdrop of monsoon melancholy against which her voice traced the contours of unexpressed longing.",
    },
    {
      song:         "Janam Janam Ka Sath",
      singer:       SINGERS.dummy,
      lataOriginal: "Janam Janam Ka Sath Hai",
      film:         "Janam Janam Ka Sath",
      year:         "1957",
      story:        "A pledge of lifelong companionship set to a dignified melody, this song captured the devotional quality Lata brought to love songs — treating romantic commitment with the seriousness of a vow.",
    },
    {
      song:         "Sanam Tu Bewafa Ke",
      singer:       SINGERS.dummy,
      lataOriginal: "Sanam Tu Bewafa Ke",
      film:         "Ek Kali Muskayee",
      year:         "1968",
      story:        "A song of quiet reproach to an unfaithful beloved, Lata's controlled delivery of its hurt and dignity made it one of her most emotionally precise recordings of the late 1960s.",
    },
    {
      song:         "Salam-E-Ishq",
      singer:       SINGERS.dummy,
      lataOriginal: "Salam-E-Ishq Meri Jaan",
      film:         "Muqaddar Ka Sikandar",
      year:         "1978",
      story:        "Kalyanji-Anandji's grand romantic number from Muqaddar Ka Sikandar gave Lata a canvas of filmic scale; her confident rendition matched the film's sweeping ambition.",
    },
    {
      song:         "Badal Yun Garajta Hai",
      singer:       SINGERS.dummy,
      lataOriginal: "Badal Yun Garajta Hai",
      film:         "Ek Duje Ke Liye",
      year:         "1981",
      story:        "Laxmikant-Pyarelal's storm-drenched melody from Ek Duje Ke Liye became iconic; Lata's passionate, elemental rendering matched the thunderous imagery of Anand Bakshi's lyrics.",
    },
    {
      song:         "Ruk Ja Ae Hawa",
      singer:       SINGERS.dummy,
      lataOriginal: "Ruk Ja Ae Hawa",
      film:         "Do Raaste",
      year:         "1969",
      story:        "Laxmikant-Pyarelal composed this plea to the wind to linger, carrying the beloved's perfume a moment longer; Lata's rendering made the metaphor feel genuinely breathless.",
    },
    {
      song:         "Hum Dono Do Premi",
      singer:       SINGERS.dummy,
      lataOriginal: "Hum Dono Do Premi",
      film:         "Ajnabee",
      year:         "1974",
      story:        "A duet with Kishore Kumar from Ajnabee, R.D. Burman's melody captures two lovers suspended in a moment of perfect, uncomplicated happiness — a rare, sunny mood in 1970s Hindi film music.",
    },
    {
      song:         "Jane Do Jane Do",
      singer:       SINGERS.dummy,
      lataOriginal: "Jane Do Jane Do Mujhe Jana Hai",
      film:         "Apna Desh",
      year:         "1972",
      story:        "A spirited Laxmikant-Pyarelal composition from the comedy Apna Desh, Lata's playful and slightly teasing rendering of this song showed her effortless ease with lighter material.",
    },
    {
      song:         "Dafli Wale",
      singer:       SINGERS.dummy,
      lataOriginal: "Dafli Wale Dafli Baja",
      film:         "Sargam",
      year:         "1979",
      story:        "Laxmikant-Pyarelal's folk-inflected melody for Sargam gave Lata a song of irresistible, dancing rhythm — one of the most immediately joyful recordings of her long career.",
    },
    {
      song:         "Naino Mein Sapna",
      singer:       SINGERS.dummy,
      lataOriginal: "Naino Mein Sapna",
      film:         "Himmatwala",
      year:         "1983",
      story:        "Bappi Lahiri's disco-influenced melody from the blockbuster Himmatwala gave Lata an unlikely but hugely successful foray into the pop sound dominating 1980s Hindi cinema.",
    },
    {
      song:         "Saware",
      singer:       SINGERS.dummy,
      lataOriginal: "Saware",
      film:         "Marathi / Folk",
      year:         "—",
      story:        "A Marathi song of longing for the beloved, the diminutive affection of the word saware — meaning the dark-complexioned one — carries a tenderness that Lata rendered with perfect simplicity.",
    },
 
    // ── Session 6 ──────────────────────────
    {
      song:         "Lag Ja Gale",
      singer:       SINGERS.dummy,
      lataOriginal: "Lag Ja Gale Se Phir",
      film:         "Woh Kaun Thi",
      year:         "1964",
      story:        "Madan Mohan's immortal melody and Raj Khosla's direction created a moment of pure cinema; Lata's recording in a single take is said to have left the entire studio in hushed disbelief.",
    },
    {
      song:         "Sunio Ji",
      singer:       SINGERS.dummy,
      lataOriginal: "Sunio Ji Maine",
      film:         "Marathi / Folk",
      year:         "—",
      story:        "A tender Marathi song of intimate address, its quiet domestic warmth is a reminder that Lata's artistry encompassed the private and unhurried as much as the grand and dramatic.",
    },
    {
      song:         "Chalte Chalte",
      singer:       SINGERS.dummy,
      lataOriginal: "Chalte Chalte Mere Yeh Geet Yaad Rakhna",
      film:         "Chalte Chalte",
      year:         "1976",
      story:        "Composed by Bappi Lahiri for the film of the same name, this song about music outlasting the singer who made it carries an unintended poignancy given Lata's own extraordinary legacy.",
    },
    {
      song:         "O Mere Shah-e-Khuba",
      singer:       SINGERS.dummy,
      lataOriginal: "O Mere Shah-e-Khuba",
      film:         "Prem Qaidi",
      year:         "1991",
      story:        "Composed by Rajesh Roshan, this romantic address of regal devotion gave Lata a melody suited to her capacity for combining grandeur with personal intimacy.",
    },
    {
      song:         "Mere Humsafar",
      singer:       SINGERS.dummy,
      lataOriginal: "Mere Humsafar Mere Paas Aao",
      film:         "Abhilasha",
      year:         "1968",
      story:        "Ravi's warm and unhurried melody from Abhilasha invited the beloved near with simple and sincere words; Lata's rendering made the invitation feel genuinely irresistible.",
    },
    {
      song:         "Wada Na Tod",
      singer:       SINGERS.dummy,
      lataOriginal: "Wada Na Tod",
      film:         "Dil Ek Mandir",
      year:         "1963",
      story:        "A song of quiet pleading not to break a promise, C. Ramchandra's melody gave Lata a framework for one of her most dignified and moving expressions of vulnerability.",
    },
    {
      song:         "Jhoot Bole Kauwa Kaate",
      singer:       SINGERS.dummy,
      lataOriginal: "Jhoot Bole Kauwa Kaate",
      film:         "Bobby",
      year:         "1973",
      story:        "Laxmikant-Pyarelal's playful number from the iconic Bobby was among Lata's most spirited comic performances — sung with Shailendra Singh, it perfectly captured youthful romantic mischief.",
    },
    {
      song:         "Papi Bichuwa",
      singer:       SINGERS.dummy,
      lataOriginal: "Chadh Gayo Papi Bichuwa",
      film:         "Madhumati",
      year:         "1958",
      story:        "Salil Chowdhury's folk-styled duet with Manna Dey from Madhumati is a joyful counterpoint to the film's tragic story — Lata's carefree playfulness here showing a side rarely seen in her dramatic work.",
    },
    {
      song:         "Sunai Deti Hai",
      singer:       SINGERS.dummy,
      lataOriginal: "Sunai Deti Hai Jiski Dhun",
      film:         "Masoom",
      year:         "1983",
      story:        "R.D. Burman composed this elusive, half-heard melody for Masoom; Lata's drifting, searching rendition captured perfectly the song's quality of music felt rather than fully heard.",
    },
    {
      song:         "Chunri Sambhal Gori",
      singer:       SINGERS.dummy,
      lataOriginal: "Chunri Sambhal Gori",
      film:         "Baharon Ke Sapne",
      year:         "1967",
      story:        "R.D. Burman's debut film score gave the world this cheerful warning to a young woman to hold her scarf — Lata's spirited rendering launched one of Hindi cinema's most celebrated composer careers.",
    },
    {
      song:         "Jai Jai Shiv Shankar",
      singer:       SINGERS.dummy,
      lataOriginal: "Jai Jai Shiv Shankar",
      film:         "Aap Ki Kasam",
      year:         "1974",
      story:        "Originally a duet with Kishore Kumar composed by R.D. Burman, this exuberant Holi celebration song became one of the most played festival numbers in the history of Hindi film music.",
    },
    {
      song:         "Ooi Ma Ooi Ma Ye Kya",
      singer:       SINGERS.dummy,
      lataOriginal: "Ooi Ma Ooi Ma",
      film:         "Padosan",
      year:         "1968",
      story:        "R.D. Burman's comic masterpiece from Padosan gave Lata a song of mock-dramatic distress — she delivered its humour with impeccable timing, proving comedy is as demanding a craft as tragedy.",
    },
    {
      song:         "Zumta Mausam",
      singer:       SINGERS.dummy,
      lataOriginal: "Jhoomta Mausam Mast Mahina",
      film:         "Souten",
      year:         "1983",
      story:        "Usha Khanna composed this warm seasonal melody for Souten; Lata's buoyant rendering captured the swaying, languid quality of a pleasant afternoon that the lyrics evoke so vividly.",
    },
    {
      song:         "Ek Tu Hi Bharosa",
      singer:       SINGERS.dummy,
      lataOriginal: "Ek Tu Hi Bharosa Ek Tu Hi Sahara",
      film:         "Pran Jaye Par Vachan Na Jaye",
      year:         "1974",
      story:        "A devotional of complete trust, Laxmikant-Pyarelal's composition gave Lata a song of surrender that she rendered with the same sincerity she brought to her bhakti recordings.",
    },
    {
      song:         "O Mor Moyna Go",
      singer:       SINGERS.dummy,
      lataOriginal: "O Mor Moyna Go",
      film:         "Bengali Folk",
      year:         "—",
      story:        "A beloved Bengali folk song, Lata recorded several Bengali songs across her career with a linguistic ease that reflected her systematic study of each language she sang in.",
    },
    {
      song:         "Jiya Jale",
      singer:       SINGERS.dummy,
      lataOriginal: "Jiya Jale Jaan Jale",
      film:         "Dil Se",
      year:         "1998",
      story:        "A.R. Rahman composed this hypnotic South Indian-flavoured melody for Mani Ratnam's Dil Se; Lata's voice moved through it like smoke — elemental, unhurried, and impossible to pin down.",
    },
    {
      song:         "Sare Jahan Se Accha",
      singer:       SINGERS.dummy,
      lataOriginal: "Sare Jahan Se Accha Hindustan Hamara",
      film:         "Patriotic — Live",
      year:         "1905",
      story:        "Written by Allama Iqbal in 1905, this patriotic poem was recorded by Lata multiple times across her career; each recording renewed the song's promise of an India that inspires love rather than commands it.",
    },
    {
      song:         "Ae Mere Watan Ke Logo",
      singer:       SINGERS.dummy,
      lataOriginal: "Ae Mere Watan Ke Logo",
      film:         "Patriotic — Live",
      year:         "1963",
      story:        "Written by Kavi Pradeep and composed by C. Ramchandra, Lata sang this at the 1963 Republic Day parade in memory of soldiers fallen in the Sino-Indian War — Prime Minister Nehru wept openly.",
    },
    {
      song:         "Mile Sur Mera Tumhara",
      singer:       SINGERS.dummy,
      lataOriginal: "Mile Sur Mera Tumhara",
      film:         "Doordarshan — National Integration",
      year:         "1988",
      story:        "Composed by Louis Banks to Piyush Pandey's concept, this national integration anthem featured Lata alongside singers across India's languages — her participation lending the project its greatest dignity.",
    },
  ],
}

export default CONFIG