```typescript
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Geist sans-serif font configuration for the application.
 *
 * @remarks
 * Configures the Geist font with a CSS variable and Latin subset for use throughout the app.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Geist monospace font configuration for the application.
 *
 * @remarks
 * Configures the Geist Mono font with a CSS variable and Latin subset for use throughout the app.
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Application metadata for SEO and document head configuration.
 *
 * @remarks
 * Exported metadata object used by Next.js to set the page title and description.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component for the application.
 *
 * @remarks
 * Wraps all pages with the HTML and body structure, applying font variables and base styling.
 *
 * @param props - The component props.
 * @param props.children - The page content to be rendered within the layout.
 * @returns The root HTML structure with font classes, layout styling, and child content.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
```